### PR TITLE
Add support for keyword arguments

### PR DESCRIPTION
**Pull request by mvastola**
Drops support for rubies < 2.0

### CODE REVIEW

**Comment by olimart** [comment]
@codeodor can you please merge this one 🙏 
(and potentially move CI https://github.com/codeodor/minitest-stub_any_instance/issues/16#issuecomment-936567817)

**Comment by codeodor** [comment]
Hey thanks for the contribution @mvastola and thanks for drawing my attention to it @olimart! I apologize, but somehow this got buried in my email and I never noticed it.

**Comment by codeodor** [comment]
I merged but there is an error in the tests.

**Comment by codeodor** [comment]
Ok, I see https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/ and this this is where the error lies. Your PR addressed Ruby 3.0 but kwargs I think worked OK before this.

**Comment by codeodor** [comment]
Y'all want to check out the `master` branch and let me know how it works for you?

**Comment by codeodor** [comment]
Finally got it working on CI, dropped support (due to bundler) on some old ruby versions, and pushed a new gem. Thanks for your help in getting it up and running!

**Pull request merged**
